align_entries = true
align_comments = true
align_single_comments = true
array_trailing_comma = true
array_auto_expand = false
inline_table_expand = false
array_auto_collapse = false
compact_arrays = false
compact_inline_tables = false
compact_entries = false
column_width = 120
indent_tables = true
indent_entries = false
indent_string = "\t"
trailing_newline = true
reorder_keys = true
reorder_arrays = false
reorder_inline_tables = true
allowed_blank_lines = 1
crlf = false